use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :weekly_pickem, WeeklyPickemWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: ["node_modules/.bin/webpack-dev-server", "--inline", "--colors", "--hot", "--stdin", "--host", "localhost", "--port", "8080", "--public", "localhost:8080",
    cd: Path.expand("../assets", __DIR__)
  ]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :weekly_pickem, :environment, :dev

# Watch static and templates for browser reloading.
config :weekly_pickem, WeeklyPickemWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg|scss)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/weekly_pickem_web/views/.*(ex)$},
      ~r{lib/weekly_pickem_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :weekly_pickem, WeeklyPickem.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "weekly_pickem_dev",
  hostname: "localhost",
  pool_size: 10

# Configure Scheduler
config :weekly_pickem, WeeklyPickem.Scheduler,
  jobs: [
    {"*/15 * * * *", {WeeklyPickem.Services.MatchUpdate, :update_all_old_matches, []}}
  ]

import_config "dev.secret.exs"
